Handle invalid ingredient adding fixes #236
AY2324S1-CS2113-F11-2/tp pull request #239
Opened 2023-11-10 03:27 UTC by kaijie0102

fixes #236

2023-11-10 04:47 UTC, StanleyW00 requested changes
There is one part that should be abstracted. Other than that, LGTM.

2023-11-10 04:47 UTC, StanleyW00 commented on src/main/java/essenmakanan/command/UseIngredientCommand.java
> +        }
Should this part be abstracted so it is not too nested?

2023-11-10 12:23 UTC, charkty approved these changes
Small changes to be made, overall very neat code!

2023-11-10 12:23 UTC, charkty commented on src/main/java/essenmakanan/command/UseIngredientCommand.java
> +            updateIngredientQuantity(ingredient);
Would it be better to do if(!ingredient.isEmpty()){...} so that everything is handled within the if statement?

2023-11-10 12:23 UTC, charkty commented on src/main/java/essenmakanan/command/UseIngredientCommand.java
> +                this.ingredients.updateIngredient(newIngredient);
I like the consistency in this if statement where Single Level of Abstraction Principle is used!

2023-11-10 12:23 UTC, charkty commented on src/main/java/essenmakanan/ui/Ui.java
> +    public static void printNegativeIngredientQuantity() {
Would it be better to name it printNegativeQuantityErrorMessage ?

2023-11-10 12:23 UTC, charkty commented on src/test/java/essenmakanan/parser/IngredientParserTest.java
I like your consideration of errors thrown!

2023-11-11 03:18 UTC, StanleyW00 approved these changes

2023-11-11 03:18 UTC, merged